### ISSUE TITLE
Loader gets crashed in iOS 13

### ISSUE THREAD

**Issue by hilajqinnovation** [SachK13/SKActivityIndicatorView#11]
The loader gets crashed in SKActivityIndicatorView.swift, inside configureActivityIndicator(withStatusMessage:, isUserInteractionEnabled:) method.
The crash is actually happened in these lines,
if activityIndicatorView?.superview == nil && userInteractionStatus == false {
            backgroundView = UIView.init(frame: window!.frame)
            backgroundView!.backgroundColor = backgroundViewColor
            window!.addSubview(backgroundView!)
            backgroundView!.addSubview(activityIndicatorView!)
        } else {
            window!.addSubview(activityIndicatorView!)
        }

here in the first line. and I checked the backgroundView is getting nil.  Also the pod is not updated to support iOS 13. Please help.

**Comment by aliwaseem72** [comment]
You can resolve it to comment **" var window: UIWindow?"** if its not needed. But I need to use UIWindow for webview, in older version of iOS for webview I need to add "var window: UIWindow?". So I'm stuck because there is I can't add OS version check.
Please help me if there is a solution you found.

**Comment by aliwaseem72** [comment]
@SachK13 Have you any idea to resolve it. Because due to the use of WKWebView I need to add **var window: UIWindow?** for older version support, and It crashed for iOS 13. If I remove the **var window: UIWindow?** then I get the crash for WKWebView in older versions, and it solution to add var window: UIWindow? in app delegate.

**Comment by SachK13** [comment]
@hilajqinnovation @aliwaseem72 This has been fixed in 1.0.0. and code has been updated to support iOS 13 and above with Swift 5.x+.
